# This is a basic workflow to help you get started with Actions

name: ki_devops3_build

# Controls when the action will run. 
on:
  
  push:
    # Triggers the workflow on push events for the branches start with release
    #branches:: [ 'release/**' ]

    # Triggers the workflow on push events but only for the master branch
    branches: [ master ]

    # Triggers the workflow on push tag
    #tags: ['*']
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  merge_group:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "devops3_build"
  devops3_build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run build
        run: |
           set -e
           
           
           echo docker build ...
           docker build -t docker.lith.cloud:4/project/booking .
           
           echo docker push ...
           docker push docker.lith.cloud:4/project/booking
           
           echo build succeed!
           
           echo deploy ...
           curl https://jenkins.lith.cloud:4/generic-webhook-trigger/invoke?token=booking_123456
           echo triggerred deploying in server, please wait for some time.
           
           
           
